version: '3'

services:

    nginx:
        image: nginx:latest
        container_name: nginx-tms
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

        ports:
            - "8060:80"
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-tms
        volumes:
            - ./src:/var/www/html
        ports:
            - "127.0.0.1:9000:9000"  # Only accessible from host machine
        networks:
            - laravel

networks:
  laravel:
    external: true
    name: laravel_shared